.TH BTDU 1
.SH NAME
btdu \- sampling disk usage profiler for btrfs
.SH SYNOPSIS
\fBbtdu\fP [\fIOPTION\fP]... \fIPATH\fP
.SH DESCRIPTION
.B btdu
is a sampling disk usage profiler for btrfs.

For a detailed description, please see the full documentation:

.I https://github.com/CyberShadow/btdu#readme
.SH OPTIONS

.TP
\fIPATH\fP
Path to the root of the filesystem to analyze

.TP
\fB-j\fP, \fB--procs\fP=\fIN\fP
Number of sampling subprocesses

 (default is number of logical CPUs for this system)

.TP
\fB--seed\fP=\fIN\fP
Random seed used to choose samples

.TP
\fB-p\fP, \fB--physical\fP
Measure physical space (instead of logical).

.TP
\fB-x\fP, \fB--expert\fP
Expert mode: collect and show additional metrics.

Uses more memory.

.TP
\fB-i\fP, \fB--interval\fP=\fIDURATION\fP
Set UI refresh interval.

Specify 0 to refresh as fast as possible.

.TP
\fB--headless\fP
Run without launching the result browser UI.

.TP
\fB-n\fP, \fB--max-samples\fP=\fIN\fP
Stop after collecting N samples.

.TP
\fB--max-time\fP=\fIDURATION\fP
Stop after running for this duration.

.TP
\fB--min-resolution\fP=\fISIZE\fP
Stop after achieving this resolution (e.g. "1MB" or "1%").

.TP
\fB-o\fP, \fB--export\fP=\fIPATH\fP
On exit, export the collected results to the given file.

.TP
\fB--export-seen-as\fP
When exporting, include 'seenAs' data showing shared paths.

.TP
\fB--prefer\fP=\fIPATTERN\fP
Prioritize allocating representative samples in the given path.

.TP
\fB--ignore\fP=\fIPATTERN\fP
Deprioritize allocating representative samples in the given path.

.TP
\fB--du\fP
On exit, export represented size estimates in 'du' format to standard output.

.TP
\fB-f\fP, \fB--import\fP
Instead of analyzing a btrfs filesystem, read previously collected results saved with --export from PATH.

.TP
\fB-c\fP, \fB--compare\fP=\fIPATH\fP
Compare against a baseline from a previously exported file.

.SH BUGS
Please report defects and enhancement requests to the GitHub issue tracker:

.I https://github.com/CyberShadow/btdu/issues

.SH AUTHORS

\fBbtdu\fR is written by Vladimir Panteleev <btdu@c\fRy.m\fRd> and contributors:

.I https://github.com/CyberShadow/btdu/graphs/contributors
